version: "3.7"
services:
  neo4j:
    image: neo4j:4.0
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
